# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hplogreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to='hplogreg.User')),
            ],
        ),
    ]
