# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='myuser',
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
